export const locations = [
  {
    country: "바티칸",
    region: "바티칸",
    image: "image/vatican.jpeg",
    link: "locations/vatican.html",
    date: "2022-07-09",
  },

  {
    country: "프랑스",
    region: "베르사유",
    image: "image/versailles.jpeg",
    link: "locations/versailles.html",
    date: "2023-08-19",
  },
  {
    country: "헝가리",
    region: "티하니",
    image: "image/tihany.jpeg",
    link: "locations/tihany.html",
    date: "2023-09-04",
  },
  {
    country: "스위스",
    region: "쉴트호른",
    image: "image/Schilthorn.jpeg",
    link: "locations/Schilthorn.html",
    date: "2023-08-24",
  },
  {
    country: "대한민국",
    region: "경주",
    image: "image/gyeongju.jpeg",
    link: "locations/gyeongju.html",
    date: "2023-11-12",
  },
  {
    country: "이탈리아",
    region: "로마",
    image: "image/rome.jpeg",
    link: "locations/rome.html",
    date: "2022-07-10",
  },
  {
    country: "카타르",
    region: "도하",
    image: "image/doha.jpeg",
    link: "locations/doha.html",
    date: "2022-11-25",
  },
  {
    country: "오스트리아",
    region: "빈",
    image: "image/vienna.jpeg",
    link: "locations/vienna.html",
    date: "2023-08-28",
  },
  {
    country: "프랑스",
    region: "아네씨",
    image: "image/annecy.jpeg",
    link: "locations/annecy.html",
    date: "2023-08-23",
  },
  {
    country: "포르투갈",
    region: "세투발",
    image: "image/setubal.jpeg",
    link: "locations/setubal.html",
    date: "2023-08-12",
  },
  {
    country: "네덜란드",
    region: "암스테르담",
    image: "image/amsterdam.jpeg",
    link: "locations/amsterdam.html",
    date: "2023-08-06",
  },
  {
    country: "포르투갈",
    region: "리스본",
    image: "image/lisbon.jpeg",
    link: "locations/lisbon.html",
    date: "2023-08-16",
  },
  {
    country: "인도네시아",
    region: "덴파사르",
    image: "image/denpasar.jpeg",
    link: "locations/denpasar.html",
    date: "2022-06-09",
  },
];
